### ISSUE TITLE
Atomic Interactions Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/atomic-interactions#59]
## Design
- [x] **Design doc created** (Date: 05/08/2014) 
  - [x] Make phethelp@gmail.com owner, share with phet-team
  - [x] Add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
- [x] **Legacy sim docs/info gathered**
- [x] **Learning goals and standards identified** (Date: 07/16/2015)
- [x] **Design concept complete**  (Date: 10/07/2014)
- [x] **Wireframes complete** (Date: 10/08/2014) 
- [x] **Mockups complete** (Date: 10/22/2014) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Interviews complete** (Date: 08/10/2016) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 09/16/2016) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide
  - [x] Compatible activities ([author spreadsheet](https://docs.google.com/spreadsheets/d/1AOc1vy0HfEeJQ9sT0Vs_sr6dqmsEHfq7HWUBGQV_VQA/edit#gid=0))
  - [x] Update [Gooru spreadsheet](https://docs.google.com/spreadsheets/d/13qvc7e71zTTjaJ2VcYhhU0rNxvH4kYFnoScVCOvvf7U/edit#gid=1717560774)
  - [x] Sim primer (Tracking in #67)
  - [x] Verify credits
- [x] **Add to Edmodo**
## Implementation
- [x] **Sim repo created** (Date: 10/15/2014) 
  - [x] Simula-rasa used to create basic project structure
  - [x] Grunt unpublished-readme run to create the initial readme file
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] Standard label set applied
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can
    be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked
    to pull from rosetta to avoid conflicts.
- [x] **Initial development started** (Date: 12/17/2014)
- [x] **Sim feature complete** (Date: 02/26/2015) 
- [x] **Code review complete** (Date: 05/11/2015) 
  - [x] Code review checklist
  - [x] Model description 
- [x] **Published** (Date: 09/26/2016)
  - [x] Update repo README to published template
## QA
- [x] **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing complete** (Date: 09/07/2016) 
- [x] **First release candidate** (Date: 09/09/2016)
  - [x] phethelp@gmail.com owner of test matrix, share with phet-team, add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
  - [x] Test matrix deemed complete

**Comment by arouinfar** [comment]
Description, Learning Goals, Main Topics, etc. have been updated/identified as necessary. See the <a href="https://docs.google.com/document/d/1-2v8rQlwgWwqinYYiFu8PBIpRU7HL_InBIAtwpSzBMY/edit#heading=h.mv3glozfezqu">Website Info</a> section of the design doc.

The following activities can be moved over to the HTML5 version as well:
<img width="579" alt="screen shot 2016-09-16 at 6 24 06 pm" src="https://cloud.githubusercontent.com/assets/8419308/18604518/cde8689c-7c3a-11e6-9f65-cf096256b914.png">

Here are two options for the screenshot @jbphet. Argon has a deeper (easier to see) well, but neon was used in the Java version's screenshot. I'm okay with either option.
<a href="https://cloud.githubusercontent.com/assets/8419308/18604585/98b4c5a2-7c3b-11e6-96b7-16e4d804323e.png">atomic_interactions_screenshot_argon.png</a>
<a href = "https://cloud.githubusercontent.com/assets/8419308/18604594/b48c3328-7c3b-11e6-9d41-b5ac9eec727d.png">atomic_interactions_screenshot_neon.png</a>

<img width="512" alt="atomic_interactions_screenshot_argon" src="https://cloud.githubusercontent.com/assets/8419308/18604605/c2b3bc1e-7c3b-11e6-8eda-eb68f9a2c828.png">
<img width="512" alt="atomic_interactions_screenshot_neon" src="https://cloud.githubusercontent.com/assets/8419308/18604606/c2b89f90-7c3b-11e6-8ea3-5811cf6d0520.png">

**Comment by arouinfar** [comment]
<a href="https://drive.google.com/drive/u/0/folders/0BwW3aJP5Cq8oem0xNnlyWUdxZWM">Teacher Tips</a> have been uploaded to Drive.

**Comment by arouinfar** [comment]
@ariel-phet  -- I may be out of the office when it's time to publish this sim, but everything is ready to go. Perhaps @phet-steele can take care of publication if I'm not around?

There are just a few things left to do:
- [x] Update <a href="https://docs.google.com/document/d/1-2v8rQlwgWwqinYYiFu8PBIpRU7HL_InBIAtwpSzBMY/edit#heading=h.mv3glozfezqu">Description, Learning Goals, and Categories</a> as provided in the design doc. I've already updated the metadata of the Java sim to make sure the appropriate Main Topics, Keywords, etc. have been tagged and properly arranged, so those should transfer over to HTML5. 
- [x] Upload <a href="https://drive.google.com/drive/u/0/folders/0BwW3aJP5Cq8oem0xNnlyWUdxZWM">Teacher Tips</a>
- [x] Move over the compatible activities (see screenshot above)
- [x] NSDL Science Literacy Maps should match Java: SMS-MAP-1349, SMS-MAP-1325, SMS-BMK-1804
- [x] Update credits 

<b>Design Team:</b>
Yuen-ying Carpenter (lead designer, HTML5)
Amy Rouinfar (lead designer, HTML5)
Paul Beale (lead designer, Java)
Sarah McKagan (lead designer, Java)
Emily Moore (lead designer, Java)
Noah Podelefsky (lead designer, Java)
John Blanco (developer)
Wendy Adams
Jack Barbera 
Amy Hanson
Kelly Lancaster
Ariel Paul
Kathy Perkins
Carl Wieman

<b>Thanks to:</b>
Actual Concepts

**Comment by jbphet** [comment]
@arouinfar - I'm going with the argon version of the screenshot, at least for now.

**Comment by arouinfar** [comment]
Sounds good @jbphet. Thanks!

**Comment by ariel-phet** [comment]
@arouinfar and @amyh-phet just sim primer and pasting notes into the design document (I forget who did interviews)

(and yes I know sim primer will be awhile)

**Comment by arouinfar** [comment]
@ariel-phet I still need to take care of the notes. @amyh-phet has said she'll eventually do the primer.

**Comment by amyh-phet** [comment]
@arouinfar  Sim primer is up on website.  Removing my assignment.
